#!/usr/bin/env python

# This file is a part of IoT-LAB gateway_code
# Copyright (C) 2015 INRIA (Contact: admin@iot-lab.info)
# Contributor(s) : see AUTHORS file
#
# This software is governed by the CeCILL license under French law
# and abiding by the rules of distribution of free software.  You can  use,
# modify and/ or redistribute the software under the terms of the CeCILL
# license as circulated by CEA, CNRS and INRIA at the following URL
# http://www.cecill.info.
#
# As a counterpart to the access to the source code and  rights to copy,
# modify and redistribute granted by the license, users are provided only
# with a limited warranty  and the software's author,  the holder of the
# economic rights,  and the successive licensors  have only  limited
# liability.
#
# The fact that you are presently reading this means that you have had
# knowledge of the CeCILL license and that you accept its terms.

# Use docker-run to run the gateway in a container

import os
import sys

import argparse
import tempfile


def main(args):
    args.daemon = '-d' if args.daemon else '--rm'
    args.reloader = '-e RELOADER=1' if args.reloader else ''

    if args.control_node_type != 'no' and args.cntty is None:
        raise argparse.ArgumentError('cntty', 'cntty is needed when a control node is used')

    # Writing local gateway configuration
    cfg_dir = tempfile.mkdtemp()
    with open(os.path.join(cfg_dir, 'board_type'), 'w') as f:
        f.write(args.board_type)

    with open(os.path.join(cfg_dir, 'control_node_type'), 'w') as f:
        f.write(args.control_node_type)

    with open(os.path.join(cfg_dir, 'hostname'), 'w') as f:
        f.write(args.hostname)

    args.cfg_dir = '-v %s:/var/local/config' % cfg_dir

    running = '''
    docker run \
      {0.volume} \
      {0.cfg_dir} \
      {0.ontty} \
      {0.cntty} \
      {0.reloader} \
      -p 8080:8080 \
      -p 20000:20000 \
      --name "gateway_test" \
      --privileged \
      {0.daemon} \
      iot-lab-gateway
    '''.format(args)

    print('running docker command:')
    print(running)

    os.system(running)


def volume_type(input_str):
    if input_str != '':
        return ('-v {}:/home/iot-lab-gateway'
                .format(os.path.abspath(input_str)))
    else:
        return ''


def tty_type(prefix):
    def func(input_str):
        return '-v %s:/dev/tty%s' % (os.path.realpath(input_str), prefix)
    return func


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        add_help=False, formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--help', action='help')
    parser.add_argument('-v', '--volume', dest='volume', type=volume_type,
                        help='Host directory containing iot-lab-gateway code (usually $PWD)',
                        default='')
    parser.add_argument('-b', '--board-type', dest='board_type', default='m3',
                        help='Set node board type')
    parser.add_argument('-h', '--hostname', dest='hostname',
                        default='custom-123',
                        help='Set hostname')
    parser.add_argument('-c', '--control-node-type', dest='control_node_type',
                        default='no',
                        help='Set node as control node')
    parser.add_argument('-d', '--daemon', dest='daemon', action='store_true',
                        help='Daemon mode')
    parser.add_argument('-r', '--reloader', dest='reloader',
                        action='store_true', help='Reloader')
    parser.add_argument('--cntty', dest='cntty', type=tty_type('CN'), default='',
                        help='Control Node tty to pass inside the docker container')
    parser.add_argument('ontty', type=tty_type('ON'),
                        help='Open Node tty to pass inside the docker container')
    main(parser.parse_args(sys.argv[1:]))
