#!/bin/sh
#
# Init script for Gateway Server using bottle
# http://bottlepy.org
#
set -x
DESC="Gateway Server"
NAME=gateway_server
PIDDIR=/var/run/${NAME}
PIDFILE=$PIDDIR/${NAME}.pid
LOGDIR=/var/log/${NAME}
LOGFILE=$LOGDIR/${NAME}.log
DAEMONUSER=www-data
DAEMON=/usr/bin/server_rest.py



case "$1" in
  start)
    echo "Starting $DESC ... "
    if [ ! -d $PIDDIR ]; then
         mkdir -p $PIDDIR
         chown $DAEMONUSER:$DAEMONUSER $PIDDIR
    fi
    if [ ! -d $LOGDIR ]; then
         mkdir -p $LOGDIR
         chown $DAEMONUSER:$DAEMONUSER $LOGDIR
    fi
    start-stop-daemon --start -m --pidfile $PIDFILE -b --chuid $DAEMONUSER:$DAEMONUSER --exec /bin/bash -- -c "exec $DAEMON >> $LOGFILE 2>&1"
    ;;
  stop)
    echo "Stopping $DESC ... "
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE
    # Many daemons don't delete their pidfiles when they exit.
    rm -f $PIDFILE
    ;;
  restart)
    echo -n "Restarting $DESC ... "
    $0 stop
    sleep 5
    $0 start
    ;;
  status)
    PID=`/bin/ps -eo 'pid,cmd'| grep $DAEMON | grep -v grep | awk '{sub("^ ", "", $0); print $0}' | cut -d " " -f 1`
    if [[ -n "$PID" ]]; then
       echo "$DESC (pid $PID) is running."
    else
       echo "$DESC is stopped."
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/bottle {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0

