#! /bin/sh -x

sleep 3
echo config_consumption_measure stop
sleep 1
echo start battery
sleep 1
echo stop battery
sleep 1
echo stop dc
sleep 1
echo start dc
sleep 1
echo reset_time
sleep 1
echo config_consumption_measure start 3.3V p 1 v 1 c 1 -p 1100us -a 512
sleep 5
echo config_consumption_measure start 3.3V p 0 v 1 c 0 -p 1100us -a 512
sleep 5
echo reset_time
sleep 5
echo config_consumption_measure stop
