name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  python-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
        sudo apt-get install socat
    - name: Test with tox
      run: |
        tox -e py$(echo ${{ matrix.python-version }} | tr -d .)-tests
    - name: Check style
      if: ${{ matrix.python-version == 3.9 }}
      run: |
        tox -e py$(echo ${{ matrix.python-version }} | tr -d .)-lint
        tox -e copying
    - name: Upload coverage to Codecov
      if: ${{ matrix.python-version == 3.9 }}
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
  docker-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test within Docker image
      run: make test
  integration-test:
    runs-on: self-hosted
    strategy:
      matrix:
        boards:
          - node-id: 17
            site: devgrenoble
            archi: a8
          - node-id: 17
            site: devgrenoble
            archi: m3
          - node-id: 1 # samr21
            site: devgrenoble
            archi: custom
          - node-id: 4 # nucleo-wl55jc
            site: devgrenoble
            archi: custom
          - node-id: 29 # microbit
            site: devsaclay
            archi: custom
          - node-id: 30 # arduino-zero
            site: devsaclay
            archi: custom
          - node-id: 31 # st-lrwan1
            site: devsaclay
            archi: custom
          - node-id: 32  # nrf52dk
            site: devsaclay
            archi: custom
          - node-id: 33 # nrf52840dk
            site: devsaclay
            archi: custom
          - node-id: 4 # zigduino
            site: devstrasbourg
            archi: custom
      fail-fast: false
    steps:
      - name: Check out install-lib repo
        uses: actions/checkout@v2
        with:
          repository: iot-lab/iot-lab-dev
          token: ${{ secrets.IOTLAB_TOKEN }}
      - name: Decrypt password
        run: make decrypt_passwords
      - name: Launch integration tests
        working-directory: ./install_lib
        run: |
          fab ci:${{ matrix.boards.archi }}_ids=${{ matrix.boards.node-id }} nodes.test_gateway_code:codecov_token=${{ secrets.CODECOV_TOKEN }} -H root@${{ matrix.boards.site }}.iot-lab.info:2222
