name: python-test

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test within Docker image
      run: make test
    - name: Upload coverage
      run: |
        docker run --rm                   \
        -v $PWD:/shared                   \
        -e LOCAL_USER_ID=`id -u ${USER}`  \
        fitiotlab/iot-lab-gateway-tests   \
        tox -e upload_coverage
